name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint